services:
  laravel:
    build: ./Server
    container_name: laravel
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/var/www
    depends_on:
      - postgres
    networks:
      - app-network

  vuejs:
    build: ./Client
    container_name: vue.js
    working_dir: /app
    command: npm run build
    volumes:
      - ./Client:/app
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: bd-app-conges
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Client/dist:/usr/share/nginx/html
      - ./Server/public:/var/www/public
    depends_on:
      - laravel
      - vuejs
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
